### ISSUE TITLE
how to use web4bch ?

### ISSUE THREAD

**Issue by liwei00wade** [Bitcoin-com/web3bch#1]
Could you give me an example ?

**Comment by paOol** [comment]
here is an example of `sendTransaction`
https://badgerwallet.cash/button.js  

here is an example of the `sign` method in React.js
https://github.com/paOol/react-cashid/blob/master/src/index.js

if you look at web3js documentation, it'll roughly be the same. you will have to account for the differences between ETH and BCH.

https://web3js.readthedocs.io/en/1.0/web3-eth.html

**Comment by liwei00wade** [comment]
thank you.
